import { InsertAllocationsData, InsertAllocationsVariables, UpsertAllocationsData, UpsertAllocationsVariables, InsertBillabilityRuleConditionsData, InsertBillabilityRuleConditionsVariables, UpsertBillabilityRuleConditionsData, UpsertBillabilityRuleConditionsVariables, InsertBillabilityRulesData, InsertBillabilityRulesVariables, UpsertBillabilityRulesData, UpsertBillabilityRulesVariables, InsertClientTeamAllocationsData, InsertClientTeamAllocationsVariables, UpsertClientTeamAllocationsData, UpsertClientTeamAllocationsVariables, InsertDailyAllocationsData, InsertDailyAllocationsVariables, UpsertDailyAllocationsData, UpsertDailyAllocationsVariables, InsertDataImportsData, InsertDataImportsVariables, UpsertDataImportsData, UpsertDataImportsVariables, InsertPeopleData, InsertPeopleVariables, UpsertPeopleData, UpsertPeopleVariables, InsertPhaseAllocationsData, InsertPhaseAllocationsVariables, UpsertPhaseAllocationsData, UpsertPhaseAllocationsVariables, InsertProjectMonthlyRevenueData, InsertProjectMonthlyRevenueVariables, UpsertProjectMonthlyRevenueData, UpsertProjectMonthlyRevenueVariables, InsertProjectPhasesData, InsertProjectPhasesVariables, UpsertProjectPhasesData, UpsertProjectPhasesVariables, InsertProjectScopesData, InsertProjectScopesVariables, UpsertProjectScopesData, UpsertProjectScopesVariables, InsertProjectsData, InsertProjectsVariables, UpsertProjectsData, UpsertProjectsVariables, InsertRateCardsData, InsertRateCardsVariables, UpsertRateCardsData, UpsertRateCardsVariables, InsertRolesData, InsertRolesVariables, UpsertRolesData, UpsertRolesVariables, InsertTimeEntriesData, InsertTimeEntriesVariables, UpsertTimeEntriesData, UpsertTimeEntriesVariables, CreateAppUserData, CreateAppUserVariables, UpdateAppUserData, UpdateAppUserVariables, DeleteAppUserData, DeleteAppUserVariables, DeleteTimeEntriesByDateData, DeleteTimeEntriesByDateVariables, DeleteAllTimeEntriesData, DeleteBillabilityRulesData, DeleteBillabilityRulesVariables, DeleteBillabilityRuleConditionsData, DeleteBillabilityRuleConditionsVariables, DeleteBillabilityRuleConditionsByRuleData, DeleteBillabilityRuleConditionsByRuleVariables, DeletePeopleData, DeletePeopleVariables, UpdateTimeEntryPersonData, UpdateTimeEntryPersonVariables, ListProjectsData, GetProjectData, GetProjectVariables, ListPeopleData, ListRolesData, ListRateCardsData, ListTimeEntriesData, ListTimeEntriesByProjectData, ListTimeEntriesByProjectVariables, ListProjectPhasesData, ListAllocationsData, ListDataImportsData, GetAppUserByEmailData, GetAppUserByEmailVariables, ListAppUsersData, GetOldestTimeEntryData, GetNewestTimeEntryData, GetTimeEntriesByDateRangeData, GetTimeEntriesByDateRangeVariables, GetAllTimeEntriesData, ListProjectScopesData, ListBillabilityRulesData, ListBillabilityRuleConditionsData } from '../';
import { UseDataConnectQueryResult, useDataConnectQueryOptions, UseDataConnectMutationResult, useDataConnectMutationOptions} from '@tanstack-query-firebase/react/data-connect';
import { UseQueryResult, UseMutationResult} from '@tanstack/react-query';
import { DataConnect } from 'firebase/data-connect';
import { FirebaseError } from 'firebase/app';


export function useInsertAllocations(options?: useDataConnectMutationOptions<InsertAllocationsData, FirebaseError, InsertAllocationsVariables>): UseDataConnectMutationResult<InsertAllocationsData, InsertAllocationsVariables>;
export function useInsertAllocations(dc: DataConnect, options?: useDataConnectMutationOptions<InsertAllocationsData, FirebaseError, InsertAllocationsVariables>): UseDataConnectMutationResult<InsertAllocationsData, InsertAllocationsVariables>;

export function useUpsertAllocations(options?: useDataConnectMutationOptions<UpsertAllocationsData, FirebaseError, UpsertAllocationsVariables>): UseDataConnectMutationResult<UpsertAllocationsData, UpsertAllocationsVariables>;
export function useUpsertAllocations(dc: DataConnect, options?: useDataConnectMutationOptions<UpsertAllocationsData, FirebaseError, UpsertAllocationsVariables>): UseDataConnectMutationResult<UpsertAllocationsData, UpsertAllocationsVariables>;

export function useInsertBillabilityRuleConditions(options?: useDataConnectMutationOptions<InsertBillabilityRuleConditionsData, FirebaseError, InsertBillabilityRuleConditionsVariables>): UseDataConnectMutationResult<InsertBillabilityRuleConditionsData, InsertBillabilityRuleConditionsVariables>;
export function useInsertBillabilityRuleConditions(dc: DataConnect, options?: useDataConnectMutationOptions<InsertBillabilityRuleConditionsData, FirebaseError, InsertBillabilityRuleConditionsVariables>): UseDataConnectMutationResult<InsertBillabilityRuleConditionsData, InsertBillabilityRuleConditionsVariables>;

export function useUpsertBillabilityRuleConditions(options?: useDataConnectMutationOptions<UpsertBillabilityRuleConditionsData, FirebaseError, UpsertBillabilityRuleConditionsVariables>): UseDataConnectMutationResult<UpsertBillabilityRuleConditionsData, UpsertBillabilityRuleConditionsVariables>;
export function useUpsertBillabilityRuleConditions(dc: DataConnect, options?: useDataConnectMutationOptions<UpsertBillabilityRuleConditionsData, FirebaseError, UpsertBillabilityRuleConditionsVariables>): UseDataConnectMutationResult<UpsertBillabilityRuleConditionsData, UpsertBillabilityRuleConditionsVariables>;

export function useInsertBillabilityRules(options?: useDataConnectMutationOptions<InsertBillabilityRulesData, FirebaseError, InsertBillabilityRulesVariables>): UseDataConnectMutationResult<InsertBillabilityRulesData, InsertBillabilityRulesVariables>;
export function useInsertBillabilityRules(dc: DataConnect, options?: useDataConnectMutationOptions<InsertBillabilityRulesData, FirebaseError, InsertBillabilityRulesVariables>): UseDataConnectMutationResult<InsertBillabilityRulesData, InsertBillabilityRulesVariables>;

export function useUpsertBillabilityRules(options?: useDataConnectMutationOptions<UpsertBillabilityRulesData, FirebaseError, UpsertBillabilityRulesVariables>): UseDataConnectMutationResult<UpsertBillabilityRulesData, UpsertBillabilityRulesVariables>;
export function useUpsertBillabilityRules(dc: DataConnect, options?: useDataConnectMutationOptions<UpsertBillabilityRulesData, FirebaseError, UpsertBillabilityRulesVariables>): UseDataConnectMutationResult<UpsertBillabilityRulesData, UpsertBillabilityRulesVariables>;

export function useInsertClientTeamAllocations(options?: useDataConnectMutationOptions<InsertClientTeamAllocationsData, FirebaseError, InsertClientTeamAllocationsVariables>): UseDataConnectMutationResult<InsertClientTeamAllocationsData, InsertClientTeamAllocationsVariables>;
export function useInsertClientTeamAllocations(dc: DataConnect, options?: useDataConnectMutationOptions<InsertClientTeamAllocationsData, FirebaseError, InsertClientTeamAllocationsVariables>): UseDataConnectMutationResult<InsertClientTeamAllocationsData, InsertClientTeamAllocationsVariables>;

export function useUpsertClientTeamAllocations(options?: useDataConnectMutationOptions<UpsertClientTeamAllocationsData, FirebaseError, UpsertClientTeamAllocationsVariables>): UseDataConnectMutationResult<UpsertClientTeamAllocationsData, UpsertClientTeamAllocationsVariables>;
export function useUpsertClientTeamAllocations(dc: DataConnect, options?: useDataConnectMutationOptions<UpsertClientTeamAllocationsData, FirebaseError, UpsertClientTeamAllocationsVariables>): UseDataConnectMutationResult<UpsertClientTeamAllocationsData, UpsertClientTeamAllocationsVariables>;

export function useInsertDailyAllocations(options?: useDataConnectMutationOptions<InsertDailyAllocationsData, FirebaseError, InsertDailyAllocationsVariables>): UseDataConnectMutationResult<InsertDailyAllocationsData, InsertDailyAllocationsVariables>;
export function useInsertDailyAllocations(dc: DataConnect, options?: useDataConnectMutationOptions<InsertDailyAllocationsData, FirebaseError, InsertDailyAllocationsVariables>): UseDataConnectMutationResult<InsertDailyAllocationsData, InsertDailyAllocationsVariables>;

export function useUpsertDailyAllocations(options?: useDataConnectMutationOptions<UpsertDailyAllocationsData, FirebaseError, UpsertDailyAllocationsVariables>): UseDataConnectMutationResult<UpsertDailyAllocationsData, UpsertDailyAllocationsVariables>;
export function useUpsertDailyAllocations(dc: DataConnect, options?: useDataConnectMutationOptions<UpsertDailyAllocationsData, FirebaseError, UpsertDailyAllocationsVariables>): UseDataConnectMutationResult<UpsertDailyAllocationsData, UpsertDailyAllocationsVariables>;

export function useInsertDataImports(options?: useDataConnectMutationOptions<InsertDataImportsData, FirebaseError, InsertDataImportsVariables>): UseDataConnectMutationResult<InsertDataImportsData, InsertDataImportsVariables>;
export function useInsertDataImports(dc: DataConnect, options?: useDataConnectMutationOptions<InsertDataImportsData, FirebaseError, InsertDataImportsVariables>): UseDataConnectMutationResult<InsertDataImportsData, InsertDataImportsVariables>;

export function useUpsertDataImports(options?: useDataConnectMutationOptions<UpsertDataImportsData, FirebaseError, UpsertDataImportsVariables>): UseDataConnectMutationResult<UpsertDataImportsData, UpsertDataImportsVariables>;
export function useUpsertDataImports(dc: DataConnect, options?: useDataConnectMutationOptions<UpsertDataImportsData, FirebaseError, UpsertDataImportsVariables>): UseDataConnectMutationResult<UpsertDataImportsData, UpsertDataImportsVariables>;

export function useInsertPeople(options?: useDataConnectMutationOptions<InsertPeopleData, FirebaseError, InsertPeopleVariables>): UseDataConnectMutationResult<InsertPeopleData, InsertPeopleVariables>;
export function useInsertPeople(dc: DataConnect, options?: useDataConnectMutationOptions<InsertPeopleData, FirebaseError, InsertPeopleVariables>): UseDataConnectMutationResult<InsertPeopleData, InsertPeopleVariables>;

export function useUpsertPeople(options?: useDataConnectMutationOptions<UpsertPeopleData, FirebaseError, UpsertPeopleVariables>): UseDataConnectMutationResult<UpsertPeopleData, UpsertPeopleVariables>;
export function useUpsertPeople(dc: DataConnect, options?: useDataConnectMutationOptions<UpsertPeopleData, FirebaseError, UpsertPeopleVariables>): UseDataConnectMutationResult<UpsertPeopleData, UpsertPeopleVariables>;

export function useInsertPhaseAllocations(options?: useDataConnectMutationOptions<InsertPhaseAllocationsData, FirebaseError, InsertPhaseAllocationsVariables>): UseDataConnectMutationResult<InsertPhaseAllocationsData, InsertPhaseAllocationsVariables>;
export function useInsertPhaseAllocations(dc: DataConnect, options?: useDataConnectMutationOptions<InsertPhaseAllocationsData, FirebaseError, InsertPhaseAllocationsVariables>): UseDataConnectMutationResult<InsertPhaseAllocationsData, InsertPhaseAllocationsVariables>;

export function useUpsertPhaseAllocations(options?: useDataConnectMutationOptions<UpsertPhaseAllocationsData, FirebaseError, UpsertPhaseAllocationsVariables>): UseDataConnectMutationResult<UpsertPhaseAllocationsData, UpsertPhaseAllocationsVariables>;
export function useUpsertPhaseAllocations(dc: DataConnect, options?: useDataConnectMutationOptions<UpsertPhaseAllocationsData, FirebaseError, UpsertPhaseAllocationsVariables>): UseDataConnectMutationResult<UpsertPhaseAllocationsData, UpsertPhaseAllocationsVariables>;

export function useInsertProjectMonthlyRevenue(options?: useDataConnectMutationOptions<InsertProjectMonthlyRevenueData, FirebaseError, InsertProjectMonthlyRevenueVariables>): UseDataConnectMutationResult<InsertProjectMonthlyRevenueData, InsertProjectMonthlyRevenueVariables>;
export function useInsertProjectMonthlyRevenue(dc: DataConnect, options?: useDataConnectMutationOptions<InsertProjectMonthlyRevenueData, FirebaseError, InsertProjectMonthlyRevenueVariables>): UseDataConnectMutationResult<InsertProjectMonthlyRevenueData, InsertProjectMonthlyRevenueVariables>;

export function useUpsertProjectMonthlyRevenue(options?: useDataConnectMutationOptions<UpsertProjectMonthlyRevenueData, FirebaseError, UpsertProjectMonthlyRevenueVariables>): UseDataConnectMutationResult<UpsertProjectMonthlyRevenueData, UpsertProjectMonthlyRevenueVariables>;
export function useUpsertProjectMonthlyRevenue(dc: DataConnect, options?: useDataConnectMutationOptions<UpsertProjectMonthlyRevenueData, FirebaseError, UpsertProjectMonthlyRevenueVariables>): UseDataConnectMutationResult<UpsertProjectMonthlyRevenueData, UpsertProjectMonthlyRevenueVariables>;

export function useInsertProjectPhases(options?: useDataConnectMutationOptions<InsertProjectPhasesData, FirebaseError, InsertProjectPhasesVariables>): UseDataConnectMutationResult<InsertProjectPhasesData, InsertProjectPhasesVariables>;
export function useInsertProjectPhases(dc: DataConnect, options?: useDataConnectMutationOptions<InsertProjectPhasesData, FirebaseError, InsertProjectPhasesVariables>): UseDataConnectMutationResult<InsertProjectPhasesData, InsertProjectPhasesVariables>;

export function useUpsertProjectPhases(options?: useDataConnectMutationOptions<UpsertProjectPhasesData, FirebaseError, UpsertProjectPhasesVariables>): UseDataConnectMutationResult<UpsertProjectPhasesData, UpsertProjectPhasesVariables>;
export function useUpsertProjectPhases(dc: DataConnect, options?: useDataConnectMutationOptions<UpsertProjectPhasesData, FirebaseError, UpsertProjectPhasesVariables>): UseDataConnectMutationResult<UpsertProjectPhasesData, UpsertProjectPhasesVariables>;

export function useInsertProjectScopes(options?: useDataConnectMutationOptions<InsertProjectScopesData, FirebaseError, InsertProjectScopesVariables>): UseDataConnectMutationResult<InsertProjectScopesData, InsertProjectScopesVariables>;
export function useInsertProjectScopes(dc: DataConnect, options?: useDataConnectMutationOptions<InsertProjectScopesData, FirebaseError, InsertProjectScopesVariables>): UseDataConnectMutationResult<InsertProjectScopesData, InsertProjectScopesVariables>;

export function useUpsertProjectScopes(options?: useDataConnectMutationOptions<UpsertProjectScopesData, FirebaseError, UpsertProjectScopesVariables>): UseDataConnectMutationResult<UpsertProjectScopesData, UpsertProjectScopesVariables>;
export function useUpsertProjectScopes(dc: DataConnect, options?: useDataConnectMutationOptions<UpsertProjectScopesData, FirebaseError, UpsertProjectScopesVariables>): UseDataConnectMutationResult<UpsertProjectScopesData, UpsertProjectScopesVariables>;

export function useInsertProjects(options?: useDataConnectMutationOptions<InsertProjectsData, FirebaseError, InsertProjectsVariables>): UseDataConnectMutationResult<InsertProjectsData, InsertProjectsVariables>;
export function useInsertProjects(dc: DataConnect, options?: useDataConnectMutationOptions<InsertProjectsData, FirebaseError, InsertProjectsVariables>): UseDataConnectMutationResult<InsertProjectsData, InsertProjectsVariables>;

export function useUpsertProjects(options?: useDataConnectMutationOptions<UpsertProjectsData, FirebaseError, UpsertProjectsVariables>): UseDataConnectMutationResult<UpsertProjectsData, UpsertProjectsVariables>;
export function useUpsertProjects(dc: DataConnect, options?: useDataConnectMutationOptions<UpsertProjectsData, FirebaseError, UpsertProjectsVariables>): UseDataConnectMutationResult<UpsertProjectsData, UpsertProjectsVariables>;

export function useInsertRateCards(options?: useDataConnectMutationOptions<InsertRateCardsData, FirebaseError, InsertRateCardsVariables>): UseDataConnectMutationResult<InsertRateCardsData, InsertRateCardsVariables>;
export function useInsertRateCards(dc: DataConnect, options?: useDataConnectMutationOptions<InsertRateCardsData, FirebaseError, InsertRateCardsVariables>): UseDataConnectMutationResult<InsertRateCardsData, InsertRateCardsVariables>;

export function useUpsertRateCards(options?: useDataConnectMutationOptions<UpsertRateCardsData, FirebaseError, UpsertRateCardsVariables>): UseDataConnectMutationResult<UpsertRateCardsData, UpsertRateCardsVariables>;
export function useUpsertRateCards(dc: DataConnect, options?: useDataConnectMutationOptions<UpsertRateCardsData, FirebaseError, UpsertRateCardsVariables>): UseDataConnectMutationResult<UpsertRateCardsData, UpsertRateCardsVariables>;

export function useInsertRoles(options?: useDataConnectMutationOptions<InsertRolesData, FirebaseError, InsertRolesVariables>): UseDataConnectMutationResult<InsertRolesData, InsertRolesVariables>;
export function useInsertRoles(dc: DataConnect, options?: useDataConnectMutationOptions<InsertRolesData, FirebaseError, InsertRolesVariables>): UseDataConnectMutationResult<InsertRolesData, InsertRolesVariables>;

export function useUpsertRoles(options?: useDataConnectMutationOptions<UpsertRolesData, FirebaseError, UpsertRolesVariables>): UseDataConnectMutationResult<UpsertRolesData, UpsertRolesVariables>;
export function useUpsertRoles(dc: DataConnect, options?: useDataConnectMutationOptions<UpsertRolesData, FirebaseError, UpsertRolesVariables>): UseDataConnectMutationResult<UpsertRolesData, UpsertRolesVariables>;

export function useInsertTimeEntries(options?: useDataConnectMutationOptions<InsertTimeEntriesData, FirebaseError, InsertTimeEntriesVariables>): UseDataConnectMutationResult<InsertTimeEntriesData, InsertTimeEntriesVariables>;
export function useInsertTimeEntries(dc: DataConnect, options?: useDataConnectMutationOptions<InsertTimeEntriesData, FirebaseError, InsertTimeEntriesVariables>): UseDataConnectMutationResult<InsertTimeEntriesData, InsertTimeEntriesVariables>;

export function useUpsertTimeEntries(options?: useDataConnectMutationOptions<UpsertTimeEntriesData, FirebaseError, UpsertTimeEntriesVariables>): UseDataConnectMutationResult<UpsertTimeEntriesData, UpsertTimeEntriesVariables>;
export function useUpsertTimeEntries(dc: DataConnect, options?: useDataConnectMutationOptions<UpsertTimeEntriesData, FirebaseError, UpsertTimeEntriesVariables>): UseDataConnectMutationResult<UpsertTimeEntriesData, UpsertTimeEntriesVariables>;

export function useCreateAppUser(options?: useDataConnectMutationOptions<CreateAppUserData, FirebaseError, CreateAppUserVariables>): UseDataConnectMutationResult<CreateAppUserData, CreateAppUserVariables>;
export function useCreateAppUser(dc: DataConnect, options?: useDataConnectMutationOptions<CreateAppUserData, FirebaseError, CreateAppUserVariables>): UseDataConnectMutationResult<CreateAppUserData, CreateAppUserVariables>;

export function useUpdateAppUser(options?: useDataConnectMutationOptions<UpdateAppUserData, FirebaseError, UpdateAppUserVariables>): UseDataConnectMutationResult<UpdateAppUserData, UpdateAppUserVariables>;
export function useUpdateAppUser(dc: DataConnect, options?: useDataConnectMutationOptions<UpdateAppUserData, FirebaseError, UpdateAppUserVariables>): UseDataConnectMutationResult<UpdateAppUserData, UpdateAppUserVariables>;

export function useDeleteAppUser(options?: useDataConnectMutationOptions<DeleteAppUserData, FirebaseError, DeleteAppUserVariables>): UseDataConnectMutationResult<DeleteAppUserData, DeleteAppUserVariables>;
export function useDeleteAppUser(dc: DataConnect, options?: useDataConnectMutationOptions<DeleteAppUserData, FirebaseError, DeleteAppUserVariables>): UseDataConnectMutationResult<DeleteAppUserData, DeleteAppUserVariables>;

export function useDeleteTimeEntriesByDate(options?: useDataConnectMutationOptions<DeleteTimeEntriesByDateData, FirebaseError, DeleteTimeEntriesByDateVariables>): UseDataConnectMutationResult<DeleteTimeEntriesByDateData, DeleteTimeEntriesByDateVariables>;
export function useDeleteTimeEntriesByDate(dc: DataConnect, options?: useDataConnectMutationOptions<DeleteTimeEntriesByDateData, FirebaseError, DeleteTimeEntriesByDateVariables>): UseDataConnectMutationResult<DeleteTimeEntriesByDateData, DeleteTimeEntriesByDateVariables>;

export function useDeleteAllTimeEntries(options?: useDataConnectMutationOptions<DeleteAllTimeEntriesData, FirebaseError, void>): UseDataConnectMutationResult<DeleteAllTimeEntriesData, undefined>;
export function useDeleteAllTimeEntries(dc: DataConnect, options?: useDataConnectMutationOptions<DeleteAllTimeEntriesData, FirebaseError, void>): UseDataConnectMutationResult<DeleteAllTimeEntriesData, undefined>;

export function useDeleteBillabilityRules(options?: useDataConnectMutationOptions<DeleteBillabilityRulesData, FirebaseError, DeleteBillabilityRulesVariables>): UseDataConnectMutationResult<DeleteBillabilityRulesData, DeleteBillabilityRulesVariables>;
export function useDeleteBillabilityRules(dc: DataConnect, options?: useDataConnectMutationOptions<DeleteBillabilityRulesData, FirebaseError, DeleteBillabilityRulesVariables>): UseDataConnectMutationResult<DeleteBillabilityRulesData, DeleteBillabilityRulesVariables>;

export function useDeleteBillabilityRuleConditions(options?: useDataConnectMutationOptions<DeleteBillabilityRuleConditionsData, FirebaseError, DeleteBillabilityRuleConditionsVariables>): UseDataConnectMutationResult<DeleteBillabilityRuleConditionsData, DeleteBillabilityRuleConditionsVariables>;
export function useDeleteBillabilityRuleConditions(dc: DataConnect, options?: useDataConnectMutationOptions<DeleteBillabilityRuleConditionsData, FirebaseError, DeleteBillabilityRuleConditionsVariables>): UseDataConnectMutationResult<DeleteBillabilityRuleConditionsData, DeleteBillabilityRuleConditionsVariables>;

export function useDeleteBillabilityRuleConditionsByRule(options?: useDataConnectMutationOptions<DeleteBillabilityRuleConditionsByRuleData, FirebaseError, DeleteBillabilityRuleConditionsByRuleVariables>): UseDataConnectMutationResult<DeleteBillabilityRuleConditionsByRuleData, DeleteBillabilityRuleConditionsByRuleVariables>;
export function useDeleteBillabilityRuleConditionsByRule(dc: DataConnect, options?: useDataConnectMutationOptions<DeleteBillabilityRuleConditionsByRuleData, FirebaseError, DeleteBillabilityRuleConditionsByRuleVariables>): UseDataConnectMutationResult<DeleteBillabilityRuleConditionsByRuleData, DeleteBillabilityRuleConditionsByRuleVariables>;

export function useDeletePeople(options?: useDataConnectMutationOptions<DeletePeopleData, FirebaseError, DeletePeopleVariables>): UseDataConnectMutationResult<DeletePeopleData, DeletePeopleVariables>;
export function useDeletePeople(dc: DataConnect, options?: useDataConnectMutationOptions<DeletePeopleData, FirebaseError, DeletePeopleVariables>): UseDataConnectMutationResult<DeletePeopleData, DeletePeopleVariables>;

export function useUpdateTimeEntryPerson(options?: useDataConnectMutationOptions<UpdateTimeEntryPersonData, FirebaseError, UpdateTimeEntryPersonVariables>): UseDataConnectMutationResult<UpdateTimeEntryPersonData, UpdateTimeEntryPersonVariables>;
export function useUpdateTimeEntryPerson(dc: DataConnect, options?: useDataConnectMutationOptions<UpdateTimeEntryPersonData, FirebaseError, UpdateTimeEntryPersonVariables>): UseDataConnectMutationResult<UpdateTimeEntryPersonData, UpdateTimeEntryPersonVariables>;

export function useListProjects(options?: useDataConnectQueryOptions<ListProjectsData>): UseDataConnectQueryResult<ListProjectsData, undefined>;
export function useListProjects(dc: DataConnect, options?: useDataConnectQueryOptions<ListProjectsData>): UseDataConnectQueryResult<ListProjectsData, undefined>;

export function useGetProject(vars: GetProjectVariables, options?: useDataConnectQueryOptions<GetProjectData>): UseDataConnectQueryResult<GetProjectData, GetProjectVariables>;
export function useGetProject(dc: DataConnect, vars: GetProjectVariables, options?: useDataConnectQueryOptions<GetProjectData>): UseDataConnectQueryResult<GetProjectData, GetProjectVariables>;

export function useListPeople(options?: useDataConnectQueryOptions<ListPeopleData>): UseDataConnectQueryResult<ListPeopleData, undefined>;
export function useListPeople(dc: DataConnect, options?: useDataConnectQueryOptions<ListPeopleData>): UseDataConnectQueryResult<ListPeopleData, undefined>;

export function useListRoles(options?: useDataConnectQueryOptions<ListRolesData>): UseDataConnectQueryResult<ListRolesData, undefined>;
export function useListRoles(dc: DataConnect, options?: useDataConnectQueryOptions<ListRolesData>): UseDataConnectQueryResult<ListRolesData, undefined>;

export function useListRateCards(options?: useDataConnectQueryOptions<ListRateCardsData>): UseDataConnectQueryResult<ListRateCardsData, undefined>;
export function useListRateCards(dc: DataConnect, options?: useDataConnectQueryOptions<ListRateCardsData>): UseDataConnectQueryResult<ListRateCardsData, undefined>;

export function useListTimeEntries(options?: useDataConnectQueryOptions<ListTimeEntriesData>): UseDataConnectQueryResult<ListTimeEntriesData, undefined>;
export function useListTimeEntries(dc: DataConnect, options?: useDataConnectQueryOptions<ListTimeEntriesData>): UseDataConnectQueryResult<ListTimeEntriesData, undefined>;

export function useListTimeEntriesByProject(vars: ListTimeEntriesByProjectVariables, options?: useDataConnectQueryOptions<ListTimeEntriesByProjectData>): UseDataConnectQueryResult<ListTimeEntriesByProjectData, ListTimeEntriesByProjectVariables>;
export function useListTimeEntriesByProject(dc: DataConnect, vars: ListTimeEntriesByProjectVariables, options?: useDataConnectQueryOptions<ListTimeEntriesByProjectData>): UseDataConnectQueryResult<ListTimeEntriesByProjectData, ListTimeEntriesByProjectVariables>;

export function useListProjectPhases(options?: useDataConnectQueryOptions<ListProjectPhasesData>): UseDataConnectQueryResult<ListProjectPhasesData, undefined>;
export function useListProjectPhases(dc: DataConnect, options?: useDataConnectQueryOptions<ListProjectPhasesData>): UseDataConnectQueryResult<ListProjectPhasesData, undefined>;

export function useListAllocations(options?: useDataConnectQueryOptions<ListAllocationsData>): UseDataConnectQueryResult<ListAllocationsData, undefined>;
export function useListAllocations(dc: DataConnect, options?: useDataConnectQueryOptions<ListAllocationsData>): UseDataConnectQueryResult<ListAllocationsData, undefined>;

export function useListDataImports(options?: useDataConnectQueryOptions<ListDataImportsData>): UseDataConnectQueryResult<ListDataImportsData, undefined>;
export function useListDataImports(dc: DataConnect, options?: useDataConnectQueryOptions<ListDataImportsData>): UseDataConnectQueryResult<ListDataImportsData, undefined>;

export function useGetAppUserByEmail(vars: GetAppUserByEmailVariables, options?: useDataConnectQueryOptions<GetAppUserByEmailData>): UseDataConnectQueryResult<GetAppUserByEmailData, GetAppUserByEmailVariables>;
export function useGetAppUserByEmail(dc: DataConnect, vars: GetAppUserByEmailVariables, options?: useDataConnectQueryOptions<GetAppUserByEmailData>): UseDataConnectQueryResult<GetAppUserByEmailData, GetAppUserByEmailVariables>;

export function useListAppUsers(options?: useDataConnectQueryOptions<ListAppUsersData>): UseDataConnectQueryResult<ListAppUsersData, undefined>;
export function useListAppUsers(dc: DataConnect, options?: useDataConnectQueryOptions<ListAppUsersData>): UseDataConnectQueryResult<ListAppUsersData, undefined>;

export function useGetOldestTimeEntry(options?: useDataConnectQueryOptions<GetOldestTimeEntryData>): UseDataConnectQueryResult<GetOldestTimeEntryData, undefined>;
export function useGetOldestTimeEntry(dc: DataConnect, options?: useDataConnectQueryOptions<GetOldestTimeEntryData>): UseDataConnectQueryResult<GetOldestTimeEntryData, undefined>;

export function useGetNewestTimeEntry(options?: useDataConnectQueryOptions<GetNewestTimeEntryData>): UseDataConnectQueryResult<GetNewestTimeEntryData, undefined>;
export function useGetNewestTimeEntry(dc: DataConnect, options?: useDataConnectQueryOptions<GetNewestTimeEntryData>): UseDataConnectQueryResult<GetNewestTimeEntryData, undefined>;

export function useGetTimeEntriesByDateRange(vars: GetTimeEntriesByDateRangeVariables, options?: useDataConnectQueryOptions<GetTimeEntriesByDateRangeData>): UseDataConnectQueryResult<GetTimeEntriesByDateRangeData, GetTimeEntriesByDateRangeVariables>;
export function useGetTimeEntriesByDateRange(dc: DataConnect, vars: GetTimeEntriesByDateRangeVariables, options?: useDataConnectQueryOptions<GetTimeEntriesByDateRangeData>): UseDataConnectQueryResult<GetTimeEntriesByDateRangeData, GetTimeEntriesByDateRangeVariables>;

export function useGetAllTimeEntries(options?: useDataConnectQueryOptions<GetAllTimeEntriesData>): UseDataConnectQueryResult<GetAllTimeEntriesData, undefined>;
export function useGetAllTimeEntries(dc: DataConnect, options?: useDataConnectQueryOptions<GetAllTimeEntriesData>): UseDataConnectQueryResult<GetAllTimeEntriesData, undefined>;

export function useListProjectScopes(options?: useDataConnectQueryOptions<ListProjectScopesData>): UseDataConnectQueryResult<ListProjectScopesData, undefined>;
export function useListProjectScopes(dc: DataConnect, options?: useDataConnectQueryOptions<ListProjectScopesData>): UseDataConnectQueryResult<ListProjectScopesData, undefined>;

export function useListBillabilityRules(options?: useDataConnectQueryOptions<ListBillabilityRulesData>): UseDataConnectQueryResult<ListBillabilityRulesData, undefined>;
export function useListBillabilityRules(dc: DataConnect, options?: useDataConnectQueryOptions<ListBillabilityRulesData>): UseDataConnectQueryResult<ListBillabilityRulesData, undefined>;

export function useListBillabilityRuleConditions(options?: useDataConnectQueryOptions<ListBillabilityRuleConditionsData>): UseDataConnectQueryResult<ListBillabilityRuleConditionsData, undefined>;
export function useListBillabilityRuleConditions(dc: DataConnect, options?: useDataConnectQueryOptions<ListBillabilityRuleConditionsData>): UseDataConnectQueryResult<ListBillabilityRuleConditionsData, undefined>;
